# Generated by Django 3.1.5 on 2021-01-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_contactenquiries_granted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiries',
            name='phone_number',
        ),
    ]
