# Generated by Django 3.1.5 on 2021-01-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_remove_contactenquiries_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiries',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
